### ISSUE TITLE
Crashed when enter "help()" in the Python console window

### ISSUE THREAD

**Issue by iven00000000** [hugsy/cemu#38]
OS: Windows 10
When I enter the command `help()` into the Python console window, the lower left textbox in the main window, the program crashed.

**Comment by hugsy** [comment]
The Python console from `cemu` is not entirely interactive, meaning that it doesn't support paging and such. Running commands like `help()` which rely on that may cause hanging or crash of the process.

This console was meant as a feature to help on simple operations, and not as a fully functional Python console, and I won't spend time making it so since there is little value. If you have time to spend on this, I'd be happy to integrate a Pull Request.

Cheers,

**Comment by hugsy** [comment]
Closing for house keeping.
